//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriberManagementSystem.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubscriberManagementSystem.Data.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الاقامة.
        /// </summary>
        public static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحساب.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التفعيل بنجاح.
        /// </summary>
        public static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العنوان.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الجهة.
        /// </summary>
        public static string AgencyType {
            get {
                return ResourceManager.GetString("AgencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفق.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستفيد.
        /// </summary>
        public static string Beneficiary {
            get {
                return ResourceManager.GetString("Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستفيد.
        /// </summary>
        public static string BeneficiaryType {
            get {
                return ResourceManager.GetString("BeneficiaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخيم.
        /// </summary>
        public static string Camp {
            get {
                return ResourceManager.GetString("Camp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة الفئة.
        /// </summary>
        public static string CategoryRatio {
            get {
                return ResourceManager.GetString("CategoryRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمات المرور غير متطابقة.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه الثابت يحتوي على ثوابت  فرعية ولا يمكن حذفها.
        /// </summary>
        public static string ConstantHasChildren {
            get {
                return ResourceManager.GetString("ConstantHasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع جهة الاتصال.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلد الأصلية.
        /// </summary>
        public static string CountryOfOrigin {
            get {
                return ResourceManager.GetString("CountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة الحالية.
        /// </summary>
        public static string CurrentCity {
            get {
                return ResourceManager.GetString("CurrentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإيقاف.
        /// </summary>
        public static string DateOfSuspension {
            get {
                return ResourceManager.GetString("DateOfSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإيقاف يجب أن يكون لاحقًا لتاريخ العمل.
        /// </summary>
        public static string DateOfSuspensionInvalid {
            get {
                return ResourceManager.GetString("DateOfSuspensionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العمل.
        /// </summary>
        public static string DateOfWork {
            get {
                return ResourceManager.GetString("DateOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء  التفعيل  بنجاح.
        /// </summary>
        public static string Deactivation {
            get {
                return ResourceManager.GetString("Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب المصروفات الإفتراضي.
        /// </summary>
        public static string DefaultExpenseAccount {
            get {
                return ResourceManager.GetString("DefaultExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب الإيرادات الإفتراضي.
        /// </summary>
        public static string DefaultRevenueAccount {
            get {
                return ResourceManager.GetString("DefaultRevenueAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزود الخدمة الإفتراضي.
        /// </summary>
        public static string DefaultServiceProvider {
            get {
                return ResourceManager.GetString("DefaultServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف آخر مستخدم.
        /// </summary>
        public static string DeleteLastUser {
            get {
                return ResourceManager.GetString("DeleteLastUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معامل التحويل.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون تاريخ الانتهاء أكبر من تاريخ الإصدار.
        /// </summary>
        public static string ExpiryDateValidation {
            get {
                return ResourceManager.GetString("ExpiryDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء تنفيذ هذه العملية.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك حذف حسابك الخاص.
        /// </summary>
        public static string FailedDeleteLoggedAccount {
            get {
                return ResourceManager.GetString("FailedDeleteLoggedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة أكثر من عنوان افتراضي واحد لهذا المستفيد.
        /// </summary>
        public static string HasDefaultAddress {
            get {
                return ResourceManager.GetString("HasDefaultAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة أكثر من جهة اتصال افتراضية واحدة لهذا المستفيد.
        /// </summary>
        public static string HasDefaultContact {
            get {
                return ResourceManager.GetString("HasDefaultContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المنزل.
        /// </summary>
        public static string HousingStatus {
            get {
                return ResourceManager.GetString("HousingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرّف.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهوية.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الهوية.
        /// </summary>
        public static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في التحقق، يُرجى التحقق من المدخلات الخاصة بك والمحاولة مرة أخرى.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحساب غير صالح.
        /// </summary>
        public static string InvalidAccountType {
            get {
                return ResourceManager.GetString("InvalidAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الجهة المسؤولة غير صالح.
        /// </summary>
        public static string InvalidAgencyType {
            get {
                return ResourceManager.GetString("InvalidAgencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المرفق غير صالح.
        /// </summary>
        public static string InvalidAttachmentType {
            get {
                return ResourceManager.GetString("InvalidAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستفيد غير صالح.
        /// </summary>
        public static string InvalidBeneficiaryType {
            get {
                return ResourceManager.GetString("InvalidBeneficiaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صالح.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني او كلمة المرور غير صحيحة .
        /// </summary>
        public static string InvalidEmailOrPasswoed {
            get {
                return ResourceManager.GetString("InvalidEmailOrPasswoed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس: حقل إلزامي.
        /// </summary>
        public static string InvalidGnder {
            get {
                return ResourceManager.GetString("InvalidGnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الهوية غير صالح.
        /// </summary>
        public static string InvalidIdentityType {
            get {
                return ResourceManager.GetString("InvalidIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} : تنسيق الرقم غير صالح.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع جواز السفر غير صالح.
        /// </summary>
        public static string InvalidPassportType {
            get {
                return ResourceManager.GetString("InvalidPassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير صالح.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الخدمات غير صالحة.
        /// </summary>
        public static string InvalidServiceGroup {
            get {
                return ResourceManager.GetString("InvalidServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم : حقل إلزامي.
        /// </summary>
        public static string InvalidUserType {
            get {
                return ResourceManager.GetString("InvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإصدار.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر بإسم.
        /// </summary>
        public static string IssuedByName {
            get {
                return ResourceManager.GetString("IssuedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموبايل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الانجليزي.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة / الحي.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الافراد.
        /// </summary>
        public static string NumberofIndividuals {
            get {
                return ResourceManager.GetString("NumberofIndividuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة الاصلية.
        /// </summary>
        public static string OriginalCity {
            get {
                return ResourceManager.GetString("OriginalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه الصفحة تحتوي على صفحات فرعية ولا يمكن حذفها.
        /// </summary>
        public static string PageHasChildren {
            get {
                return ResourceManager.GetString("PageHasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جواز سفر .
        /// </summary>
        public static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جواز السفر.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الإصدار.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأولوية.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة يجب أن تكون بين {0}% و{100}%.
        /// </summary>
        public static string RangeRatioValidation {
            get {
                return ResourceManager.GetString("RangeRatioValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الديانة.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة المندوب.
        /// </summary>
        public static string RepresentativeCategory {
            get {
                return ResourceManager.GetString("RepresentativeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} : حقل إلزامي.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستفيد : حقل إلزامي.
        /// </summary>
        public static string RequiredBeneficiaryType {
            get {
                return ResourceManager.GetString("RequiredBeneficiaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف : حقل إلزامي.
        /// </summary>
        public static string RequiredCategory {
            get {
                return ResourceManager.GetString("RequiredCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلة القرابة : حقل إلزامي.
        /// </summary>
        public static string RequiredKinship {
            get {
                return ResourceManager.GetString("RequiredKinship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن ترك حقل الاسم فارغًا.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع : حقل إلزامي.
        /// </summary>
        public static string RequiredTypeId {
            get {
                return ResourceManager.GetString("RequiredTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الثانوي.
        /// </summary>
        public static string SecondaryAddress {
            get {
                return ResourceManager.GetString("SecondaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمة.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الخدمة.
        /// </summary>
        public static string ServiceGroup {
            get {
                return ResourceManager.GetString("ServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني.
        /// </summary>
        public static string SName {
            get {
                return ResourceManager.GetString("SName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} : يجب ان تكون عدد الاحرف على الاقل {2} ولا يتعدى {1}.
        /// </summary>
        public static string StringLengthValidation {
            get {
                return ResourceManager.GetString("StringLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إكمال العملية بنجاح.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الصحية.
        /// </summary>
        public static string TheHealthCondition {
            get {
                return ResourceManager.GetString("TheHealthCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث.
        /// </summary>
        public static string TName {
            get {
                return ResourceManager.GetString("TName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد مرات تلقي المساعدات.
        /// </summary>
        public static string TotalAid {
            get {
                return ResourceManager.GetString("TotalAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني موجود بالفعل، يُرجى اختيار بريد إلكتروني مختلف.
        /// </summary>
        public static string UniqueEmail {
            get {
                return ResourceManager.GetString("UniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم موجود بالفعل، يُرجى اختيار اسم مختلف.
        /// </summary>
        public static string UniqueName {
            get {
                return ResourceManager.GetString("UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف موجود بالفعل، يُرجى اختيار رقم هاتف مختلف.
        /// </summary>
        public static string UniquePhoneNo {
            get {
                return ResourceManager.GetString("UniquePhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الواتساب.
        /// </summary>
        public static string WhatsAppNumber {
            get {
                return ResourceManager.GetString("WhatsAppNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العمل.
        /// </summary>
        public static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
    }
}
