//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriberManagementSystem.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubscriberManagementSystem.Web.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقبل.
        /// </summary>
        public static string Accepts {
            get {
                return ResourceManager.GetString("Accepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقبل مندوب.
        /// </summary>
        public static string AcceptsRepresentative {
            get {
                return ResourceManager.GetString("AcceptsRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Accessdenied {
            get {
                return ResourceManager.GetString("Accessdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية الوصول إلى هذا المورد.
        /// </summary>
        public static string AccessdeniedMessage {
            get {
                return ResourceManager.GetString("AccessdeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تدمير كلي.
        /// </summary>
        public static string TotalDestruction
        {
            get {
                return ResourceManager.GetString("TotalDestruction", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to نظام ادارة المخيم.
        /// </summary>
        public static string SubscriberManagementSystem
        {
            get
            {
                return ResourceManager.GetString("SubscriberManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحساب.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدوات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة  نوع الجهة.
        /// </summary>
        public static string AddAgencyType {
            get {
                return ResourceManager.GetString("AddAgencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مرفق.
        /// </summary>
        public static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة نوع مرفق.
        /// </summary>
        public static string AddAttachmentType {
            get {
                return ResourceManager.GetString("AddAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مستفيد.
        /// </summary>
        public static string AddBeneficiary {
            get {
                return ResourceManager.GetString("AddBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة نوع مستفيد.
        /// </summary>
        public static string AddBeneficiaryType {
            get {
                return ResourceManager.GetString("AddBeneficiaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة ثابت.
        /// </summary>
        public static string AddConstant {
            get {
                return ResourceManager.GetString("AddConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة جهة اتصال.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وجهة.
        /// </summary>
        public static string AddDestination {
            get {
                return ResourceManager.GetString("AddDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة هوية.
        /// </summary>
        public static string AddIdentity {
            get {
                return ResourceManager.GetString("AddIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة نوع هوية.
        /// </summary>
        public static string AddIdentityType {
            get {
                return ResourceManager.GetString("AddIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة سطر.
        /// </summary>
        public static string AddLine {
            get {
                return ResourceManager.GetString("AddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صفحة.
        /// </summary>
        public static string AddPage {
            get {
                return ResourceManager.GetString("AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة جواز سفر.
        /// </summary>
        public static string AddPassport {
            get {
                return ResourceManager.GetString("AddPassport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مكان الاقامة.
        /// </summary>
        public static string Accommodation
        {
            get
            {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to داخلي.
        /// </summary>
        public static string Indoor
        {
            get
            {
                return ResourceManager.GetString("Indoor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خارجي.
        /// </summary>
        public static string Outdoor
        {
            get
            {
                return ResourceManager.GetString("Outdoor", resourceCulture);
            }
        }
        ///  /// <summary>
        ///   Looks up a localized string similar to الحالة الصحية.
        /// </summary>
        /// 
        public static string TheHealthCondition
        {
            get
            {
                return ResourceManager.GetString("TheHealthCondition", resourceCulture);
            }
        }


        
         /// <summary>
        ///   Looks up a localized string similar to حالة العمل.
        /// </summary>
        public static string WorkStatus
        {
            get
            {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
      /// <summary>
        ///   Looks up a localized string similar to حالة السكن.
        /// </summary>
        public static string HousingStatus
        {
            get {
                return ResourceManager.GetString("HousingStatus", resourceCulture);
            }
        }

       
        /// /// <summary>
        ///   Looks up a localized string similar to عدد مرات تلقي المساعدات.
        /// </summary>
        public static string TotalAid{
            get {
                return ResourceManager.GetString("TotalAid", resourceCulture);
            }
        }

       
        public static string AddRelative {
            get {
                return ResourceManager.GetString("AddRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة المندوب.
        /// </summary>
        public static string CurrentCity
        {
            get {
                return ResourceManager.GetString("CurrentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة فئة المنودب.
        /// </summary>
        public static string OriginalCity
        {
            get {
                return ResourceManager.GetString("OriginalCity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المدينة الاصلية.
        /// </summary>
        public static string NumberofIndividuals
        {
            get {
                return ResourceManager.GetString("NumberofIndividuals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدد الافراد.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العناوين.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العنوان.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة خدمة.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مجموعة الخدمات.
        /// </summary>
        public static string AddServiceGroup {
            get {
                return ResourceManager.GetString("AddServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مستخدم.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة نوع مستخدم.
        /// </summary>
        public static string AddUserType {
            get {
                return ResourceManager.GetString("AddUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسؤول.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفق.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع المرفقات.
        /// </summary>
        public static string AttachmentsTypes {
            get {
                return ResourceManager.GetString("AttachmentsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المرفق.
        /// </summary>
        public static string AttachmentTitle {
            get {
                return ResourceManager.GetString("AttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الشخصية.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يعمل.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستفيدين.
        /// </summary>
        public static string Beneficiaries {
            get {
                return ResourceManager.GetString("Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع المستفيدين.
        /// </summary>
        public static string BeneficiariesTypes {
            get {
                return ResourceManager.GetString("BeneficiariesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستفيد.
        /// </summary>
        public static string Beneficiary {
            get {
                return ResourceManager.GetString("Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المستفيد.
        /// </summary>
        public static string BeneficiaryData {
            get {
                return ResourceManager.GetString("BeneficiaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستفيد.
        /// </summary>
        public static string BeneficiaryType {
            get {
                return ResourceManager.GetString("BeneficiaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب الصندوق.
        /// </summary>
        public static string CashAccount {
            get {
                return ResourceManager.GetString("CashAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سليم.
        /// </summary>
        public static string CategoryRatio {
            get {
                return ResourceManager.GetString("Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصاب.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقر لتنزيل المرفق.
        /// </summary>
        public static string ClickDownload {
            get {
                return ResourceManager.GetString("ClickDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقر هنا لتحميل المرفق.
        /// </summary>
        public static string ClickHereToUploadAttachment {
            get {
                return ResourceManager.GetString("ClickHereToUploadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليق.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثوابت.
        /// </summary>
        public static string Constants {
            get {
                return ResourceManager.GetString("Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة اتصال.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التواصل.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهات الاتصال.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع جهة الاتصال.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلد الأصلية.
        /// </summary>
        public static string CountryOfOrigin {
            get {
                return ResourceManager.GetString("CountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإيقاف.
        /// </summary>
        public static string DateOfSuspension {
            get {
                return ResourceManager.GetString("DateOfSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العمل.
        /// </summary>
        public static string DateOfWork {
            get {
                return ResourceManager.GetString("DateOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتراضي.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الافتراضي.
        /// </summary>
        public static string DefaultAddress {
            get {
                return ResourceManager.GetString("DefaultAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة الاتصال الافتراضية.
        /// </summary>
        public static string DefaultContact {
            get {
                return ResourceManager.GetString("DefaultContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب المصروفات الإفتراضي.
        /// </summary>
        public static string DefaultExpenseAccount {
            get {
                return ResourceManager.GetString("DefaultExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب الإيرادات الإفتراضي.
        /// </summary>
        public static string DefaultRevenueAccount {
            get {
                return ResourceManager.GetString("DefaultRevenueAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزود الخدمة الإفتراضي.
        /// </summary>
        public static string DefaultServiceProvider {
            get {
                return ResourceManager.GetString("DefaultServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب الخصم.
        /// </summary>
        public static string DiscountAccount {
            get {
                return ResourceManager.GetString("DiscountAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنزيل.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الحساب.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل العنوان.
        /// </summary>
        public static string EditAddress {
            get {
                return ResourceManager.GetString("EditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل المرفق.
        /// </summary>
        public static string EditAttachment {
            get {
                return ResourceManager.GetString("EditAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع المرفق.
        /// </summary>
        public static string EditAttachmentType {
            get {
                return ResourceManager.GetString("EditAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل المستفيد.
        /// </summary>
        public static string EditBeneficiary {
            get {
                return ResourceManager.GetString("EditBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع المستفيد.
        /// </summary>
        public static string EditBeneficiaryType {
            get {
                return ResourceManager.GetString("EditBeneficiaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الثابت.
        /// </summary>
        public static string EditConstant {
            get {
                return ResourceManager.GetString("EditConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل جهة الاتصال.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الوجهة.
        /// </summary>
        public static string EditDestination {
            get {
                return ResourceManager.GetString("EditDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الهوية.
        /// </summary>
        public static string EditIdentity {
            get {
                return ResourceManager.GetString("EditIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع الهوية.
        /// </summary>
        public static string EditIdentityType {
            get {
                return ResourceManager.GetString("EditIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصفحة.
        /// </summary>
        public static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل جواز السفر.
        /// </summary>
        public static string EditPassport {
            get {
                return ResourceManager.GetString("EditPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع جواز السفر.
        /// </summary>
        public static string EditPassportType {
            get {
                return ResourceManager.GetString("EditPassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل صلاحية.
        /// </summary>
        public static string EditPermission {
            get {
                return ResourceManager.GetString("EditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل المرافق.
        /// </summary>
        public static string EditRelative {
            get {
                return ResourceManager.GetString("EditRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل المندوب.
        /// </summary>
        public static string EditRepresentative {
            get {
                return ResourceManager.GetString("EditRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل فئة المندوب.
        /// </summary>
        public static string EditRepresentativeCategory {
            get {
                return ResourceManager.GetString("EditRepresentativeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل متطلب.
        /// </summary>
        public static string EditRequirement {
            get {
                return ResourceManager.GetString("EditRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل خدمة.
        /// </summary>
        public static string EditService {
            get {
                return ResourceManager.GetString("EditService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مجموعة الخدمات.
        /// </summary>
        public static string EditServiceGroup {
            get {
                return ResourceManager.GetString("EditServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مستخدم.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع المستخدم.
        /// </summary>
        public static string EditUserType {
            get {
                return ResourceManager.GetString("EditUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغير البريد الإلكتروني.
        /// </summary>
        public static string EmailIsChanged {
            get {
                return ResourceManager.GetString("EmailIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معامل التحويل.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتهي.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنتهاء.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.التحويل.
        /// </summary>
        public static string ExRate {
            get {
                return ResourceManager.GetString("ExRate", resourceCulture);
            }
        }
        
      
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المالية.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأول.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول (En).
        /// </summary>
        public static string FNameEn {
            get {
                return ResourceManager.GetString("FNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل نسيت كلمة المرور؟.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة.
        /// </summary>
        public static string Governorate {
            get {
                return ResourceManager.GetString("Governorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظات والمدن.
        /// </summary>
        public static string GovernoratesandCities {
            get {
                return ResourceManager.GetString("GovernoratesandCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to له تفاصيل.
        /// </summary>
        public static string HasDetails {
            get {
                return ResourceManager.GetString("HasDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايقونة.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهويات.
        /// </summary>
        public static string Identities {
            get {
                return ResourceManager.GetString("Identities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الهويات.
        /// </summary>
        public static string IdentitiesTypes {
            get {
                return ResourceManager.GetString("IdentitiesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الهوية.
        /// </summary>
        public static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الجهة المسؤولة غير صالح.
        /// </summary>
        public static string InvalidAgencyType {
            get {
                return ResourceManager.GetString("InvalidAgencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإصدار.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر بإسم.
        /// </summary>
        public static string IssuedByName {
            get {
                return ResourceManager.GetString("IssuedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الوظيفي.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلة القرابة.
        /// </summary>
        public static string Kinship {
            get {
                return ResourceManager.GetString("Kinship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخير.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب الربط.
        /// </summary>
        public static string LinkedAccount {
            get {
                return ResourceManager.GetString("LinkedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة (En).
        /// </summary>
        public static string LNameEn {
            get {
                return ResourceManager.GetString("LNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل دخول إلى حسابك.
        /// </summary>
        public static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب التسويق.
        /// </summary>
        public static string MarketingAccount {
            get {
                return ResourceManager.GetString("MarketingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسائل.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموبايل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدات النظام.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفي الشخصي.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة.
        /// </summary>
        public static string NameCity {
            get {
                return ResourceManager.GetString("NameCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الانجليزي.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الاب.
        /// </summary>
        public static string NameParent {
            get {
                return ResourceManager.GetString("NameParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة / الحي.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافي الربح.
        /// </summary>
        public static string NetProfit {
            get {
                return ResourceManager.GetString("NetProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافي الإجمالي.
        /// </summary>
        public static string NetTotal {
            get {
                return ResourceManager.GetString("NetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على صلاحيات..
        /// </summary>
        public static string NoPermissionsFound {
            get {
                return ResourceManager.GetString("NoPermissionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ بإنشاء صلاحية جديدة!.
        /// </summary>
        public static string NoPermissionsFoundMessage {
            get {
                return ResourceManager.GetString("NoPermissionsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد خدمات.
        /// </summary>
        public static string NoServices {
            get {
                return ResourceManager.GetString("NoServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة غير موجودة.
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصحفحة.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحات.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الصفحة.
        /// </summary>
        public static string PageType {
            get {
                return ResourceManager.GetString("PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوع نقدا.
        /// </summary>
        public static string PaidCash {
            get {
                return ResourceManager.GetString("PaidCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوع شيكات.
        /// </summary>
        public static string PaidChecks {
            get {
                return ResourceManager.GetString("PaidChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوع إلكترونيًا.
        /// </summary>
        public static string PaidElectronically {
            get {
                return ResourceManager.GetString("PaidElectronically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاب.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جواز السفر.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوازات السفر.
        /// </summary>
        public static string Passports {
            get {
                return ResourceManager.GetString("Passports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع جوازات السفر.
        /// </summary>
        public static string PassportsTypes {
            get {
                return ResourceManager.GetString("PassportsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع جواز السفر.
        /// </summary>
        public static string PassportType {
            get {
                return ResourceManager.GetString("PassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الميلاد.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الإصدار.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تسجيل الدخول إلى حسابك..
        /// </summary>
        public static string PleaseLogInToYourAccount {
            get {
                return ResourceManager.GetString("PleaseLogInToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق بريد.
        /// </summary>
        public static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأولوية.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        public static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يستقبل رسائل.
        /// </summary>
        public static string ReceivesMessages {
            get {
                return ResourceManager.GetString("ReceivesMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرافق.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المرافق.
        /// </summary>
        public static string RelativeData {
            get {
                return ResourceManager.GetString("RelativeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرافقين.
        /// </summary>
        public static string Relatives {
            get {
                return ResourceManager.GetString("Relatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الديانة.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتبقي.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتبقي على الحساب.
        /// </summary>
        public static string RemainingOnAccount {
            get {
                return ResourceManager.GetString("RemainingOnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المندوب.
        /// </summary>
        public static string Representative {
            get {
                return ResourceManager.GetString("Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئات المندوب.
        /// </summary>
        public static string RepresentativeCategories {
            get {
                return ResourceManager.GetString("RepresentativeCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة المندوب.
        /// </summary>
        public static string RepresentativeCategory {
            get {
                return ResourceManager.GetString("RepresentativeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المندوب.
        /// </summary>
        public static string RepresentativeName {
            get {
                return ResourceManager.GetString("RepresentativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة المندوب.
        /// </summary>
        public static string RepresentativeRatio {
            get {
                return ResourceManager.GetString("RepresentativeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المندوبين.
        /// </summary>
        public static string Representatives {
            get {
                return ResourceManager.GetString("Representatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع إلى الرئيسية.
        /// </summary>
        public static string ReturnHome {
            get {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الثانوي.
        /// </summary>
        public static string SecondaryAddress {
            get {
                return ResourceManager.GetString("SecondaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار العملة.
        /// </summary>
        public static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار  وحدة.
        /// </summary>
        public static string SelectModule {
            get {
                return ResourceManager.GetString("SelectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار  اب.
        /// </summary>
        public static string SelectParent {
            get {
                return ResourceManager.GetString("SelectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار النوع.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار نوع مستخدم.
        /// </summary>
        public static string SelectUserType {
            get {
                return ResourceManager.GetString("SelectUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمة.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفقات الخدمة.
        /// </summary>
        public static string ServiceAttachments {
            get {
                return ResourceManager.GetString("ServiceAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الخدمة.
        /// </summary>
        public static string ServiceData {
            get {
                return ResourceManager.GetString("ServiceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الخدمة.
        /// </summary>
        public static string ServiceGroup {
            get {
                return ResourceManager.GetString("ServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعات الخدمات.
        /// </summary>
        public static string ServiceGroups {
            get {
                return ResourceManager.GetString("ServiceGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الخدمة.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزود الخدمة.
        /// </summary>
        public static string ServiceProvider {
            get {
                return ResourceManager.GetString("ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متطلبات الخدمة.
        /// </summary>
        public static string ServiceRequirements {
            get {
                return ResourceManager.GetString("ServiceRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة خدمات.
        /// </summary>
        public static string ServicesBill {
            get {
                return ResourceManager.GetString("ServicesBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير الخدمات.
        /// </summary>
        public static string ServicesBills {
            get {
                return ResourceManager.GetString("ServicesBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختصارات f1.
        /// </summary>
        public static string Shortcutsf1 {
            get {
                return ResourceManager.GetString("Shortcutsf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسائل  القصيرة.
        /// </summary>
        public static string ShortMessages {
            get {
                return ResourceManager.GetString("ShortMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني.
        /// </summary>
        public static string SName {
            get {
                return ResourceManager.GetString("SName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني (En).
        /// </summary>
        public static string SNameEn {
            get {
                return ResourceManager.GetString("SNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم النظام.
        /// </summary>
        public static string SystemUser {
            get {
                return ResourceManager.GetString("SystemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضريبة.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب الضريبة.
        /// </summary>
        public static string TaxAccount {
            get {
                return ResourceManager.GetString("TaxAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث.
        /// </summary>
        public static string TName {
            get {
                return ResourceManager.GetString("TName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث (En).
        /// </summary>
        public static string TNameEn {
            get {
                return ResourceManager.GetString("TNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجمالي.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الفاتورة.
        /// </summary>
        public static string TotalBill {
            get {
                return ResourceManager.GetString("TotalBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي التكلفة.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي المدفوع.
        /// </summary>
        public static string TotalPaid {
            get {
                return ResourceManager.GetString("TotalPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترحيل.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل مرفق.
        /// </summary>
        public static string UploadAttachment {
            get {
                return ResourceManager.GetString("UploadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحيات المستخدم.
        /// </summary>
        public static string UserPermissions {
            get {
                return ResourceManager.GetString("UserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع المستخدم.
        /// </summary>
        public static string UserTypes {
            get {
                return ResourceManager.GetString("UserTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبًا بك في فاست!.
        /// </summary>
        public static string WelcomeToFast {
            get {
                return ResourceManager.GetString("WelcomeToFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الواتساب.
        /// </summary>
        public static string WhatsAppNumber {
            get {
                return ResourceManager.GetString("WhatsAppNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون.
        /// </summary>
        public static string Without {
            get {
                return ResourceManager.GetString("Without", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير بريدك الإلكتروني بنجاح. .
        /// </summary>
        public static string YorEmailIsSuccessfullyChanged {
            get {
                return ResourceManager.GetString("YorEmailIsSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
