<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SubscriberManagementSystem.Web-d4c9e064-a67f-4f8f-bd4b-e5a9472e366b</UserSecretsId>
	  <NoWarn>NU1510;NU1901;NU1902;NU1903;NU1900</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\hotkeys\.github\FUNDING.yml" />
    <None Include="wwwroot\assets\hotkeys\.github\workflows\ci.yml" />
    <None Include="wwwroot\assets\hotkeys\.husky\.gitignore" />
    <None Include="wwwroot\assets\hotkeys\.husky\pre-commit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubscriberManagementSystem.Infrastructure\SubscriberManagementSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
