<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <NoWarn>NU1510;NU1901;NU1902;NU1903;NU1900</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubscriberManagementSystem.Data\SubscriberManagementSystem.Data.csproj" />
  </ItemGroup>

</Project>
